# Use an official Python runtime as a parent image
FROM openjdk:25-jdk

# Set the working directory in the container
WORKDIR /app

# Copy the packaged jar file into the container
COPY target/*.jar app.jar

# Expose the port the app runs on
EXPOSE 44333

# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]